# Generated by Django 2.2.15 on 2023-09-01 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rg', models.CharField(max_length=20, unique=True)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('visits', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=15, unique=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.IntegerField()),
                ('role', models.CharField(max_length=80)),
                ('admission_date', models.DateField()),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StockProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.FloatField(default=0)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('base_items', models.ManyToManyField(null=True, to='core.StockProduct')),
            ],
        ),
        migrations.CreateModel(
            name='CardControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('products', models.BinaryField(default=b'\x80\x04}\x94.')),
                ('date_in', models.DateTimeField()),
                ('date_out', models.DateTimeField(null=True)),
                ('total_amount', models.FloatField(default=0.0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Customer')),
            ],
        ),
    ]
